[package]
name = "stemmefil_player"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.7.0"
midly = "0.5.2"
eframe = "0.18.0"